\set ON_ERROR_STOP on


CREATE EXTENSION IF NOT EXISTS timescaledb;


CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


CREATE TABLE IF NOT EXISTS dim_location (
    location_id VARCHAR(20) PRIMARY KEY,
    location_name VARCHAR(100) NOT NULL,
    region VARCHAR(30) NOT NULL,
    admin_type VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_dim_location_name
        UNIQUE (location_name),

    CONSTRAINT chk_dim_location_region
        CHECK (
            region IN (
                'Miền Bắc',
                'Miền Trung',
                'Miền Nam'
            )
        ),

    CONSTRAINT chk_dim_location_admin_type
        CHECK (
            admin_type IN (
                'Tỉnh',
                'Thành phố'
            )
        )
);


CREATE TABLE IF NOT EXISTS dim_monitoring_point (
    point_id VARCHAR(50) PRIMARY KEY,
    location_id VARCHAR(20) NOT NULL,
    point_name VARCHAR(150) NOT NULL,
    point_type VARCHAR(50) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_monitoring_point_location
        FOREIGN KEY (location_id)
        REFERENCES dim_location (location_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_monitoring_point_location
        UNIQUE (point_id, location_id),

    CONSTRAINT chk_monitoring_point_latitude
        CHECK (
            latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT chk_monitoring_point_longitude
        CHECK (
            longitude BETWEEN -180 AND 180
        )
);


CREATE TABLE IF NOT EXISTS fact_air_quality_hourly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    schema_version VARCHAR(20)
        NOT NULL DEFAULT '1.0',

    point_id VARCHAR(50) NOT NULL,
    location_id VARCHAR(20) NOT NULL,

    forecast_time TIMESTAMPTZ NOT NULL,

    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,

    grid_latitude DOUBLE PRECISION,
    grid_longitude DOUBLE PRECISION,

    pm2_5 DOUBLE PRECISION,
    pm10 DOUBLE PRECISION,
    carbon_monoxide DOUBLE PRECISION,
    nitrogen_dioxide DOUBLE PRECISION,
    sulphur_dioxide DOUBLE PRECISION,
    ozone DOUBLE PRECISION,

    us_aqi INTEGER,
    us_aqi_pm2_5 INTEGER,
    us_aqi_pm10 INTEGER,

    aqi_level VARCHAR(100),
    aqi_severity VARCHAR(40),

    timezone VARCHAR(100)
        NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',

    utc_offset_seconds INTEGER
        NOT NULL DEFAULT 25200,

    source VARCHAR(50)
        NOT NULL DEFAULT 'open_meteo',

    ingested_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_fact_air_quality_hourly
        PRIMARY KEY (id, forecast_time),

    CONSTRAINT uq_air_quality_point_time_source
        UNIQUE (
            point_id,
            forecast_time,
            source
        ),

    CONSTRAINT fk_air_quality_monitoring_point
        FOREIGN KEY (
            point_id,
            location_id
        )
        REFERENCES dim_monitoring_point (
            point_id,
            location_id
        )
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_air_quality_latitude
        CHECK (
            latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT chk_air_quality_longitude
        CHECK (
            longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT chk_air_quality_grid_latitude
        CHECK (
            grid_latitude IS NULL
            OR grid_latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT chk_air_quality_grid_longitude
        CHECK (
            grid_longitude IS NULL
            OR grid_longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT chk_air_quality_pm2_5
        CHECK (
            pm2_5 IS NULL
            OR pm2_5 >= 0
        ),

    CONSTRAINT chk_air_quality_pm10
        CHECK (
            pm10 IS NULL
            OR pm10 >= 0
        ),

    CONSTRAINT chk_air_quality_carbon_monoxide
        CHECK (
            carbon_monoxide IS NULL
            OR carbon_monoxide >= 0
        ),

    CONSTRAINT chk_air_quality_nitrogen_dioxide
        CHECK (
            nitrogen_dioxide IS NULL
            OR nitrogen_dioxide >= 0
        ),

    CONSTRAINT chk_air_quality_sulphur_dioxide
        CHECK (
            sulphur_dioxide IS NULL
            OR sulphur_dioxide >= 0
        ),

    CONSTRAINT chk_air_quality_ozone
        CHECK (
            ozone IS NULL
            OR ozone >= 0
        ),

    CONSTRAINT chk_air_quality_us_aqi
        CHECK (
            us_aqi IS NULL
            OR us_aqi >= 0
        ),

    CONSTRAINT chk_air_quality_us_aqi_pm2_5
        CHECK (
            us_aqi_pm2_5 IS NULL
            OR us_aqi_pm2_5 >= 0
        ),

    CONSTRAINT chk_air_quality_us_aqi_pm10
        CHECK (
            us_aqi_pm10 IS NULL
            OR us_aqi_pm10 >= 0
        ),

    CONSTRAINT chk_air_quality_severity
        CHECK (
            aqi_severity IS NULL
            OR aqi_severity IN (
                'GOOD',
                'MODERATE',
                'UNHEALTHY_SENSITIVE',
                'UNHEALTHY',
                'VERY_UNHEALTHY',
                'HAZARDOUS'
            )
        ),

    CONSTRAINT chk_air_quality_source
        CHECK (
            source = 'open_meteo'
        )
);


SELECT create_hypertable(
    'fact_air_quality_hourly',
    by_range(
        'forecast_time',
        INTERVAL '1 day'
    ),
    if_not_exists => TRUE
);


CREATE TABLE IF NOT EXISTS fact_air_quality_alerts (
    alert_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    point_id VARCHAR(50) NOT NULL,
    location_id VARCHAR(20) NOT NULL,

    alert_time TIMESTAMPTZ NOT NULL,

    aqi_value INTEGER NOT NULL,
    aqi_level VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,

    message TEXT NOT NULL,

    status VARCHAR(20)
        NOT NULL DEFAULT 'OPEN',

    source VARCHAR(50)
        NOT NULL DEFAULT 'open_meteo',

    created_at TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_alert_monitoring_point
        FOREIGN KEY (
            point_id,
            location_id
        )
        REFERENCES dim_monitoring_point (
            point_id,
            location_id
        )
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_alert_point_time_severity
        UNIQUE (
            point_id,
            alert_time,
            severity,
            source
        ),

    CONSTRAINT chk_alert_aqi_value
        CHECK (
            aqi_value >= 101
        ),

    CONSTRAINT chk_alert_severity
        CHECK (
            severity IN (
                'MEDIUM',
                'HIGH',
                'CRITICAL'
            )
        ),

    CONSTRAINT chk_alert_status
        CHECK (
            status IN (
                'OPEN',
                'ACKNOWLEDGED',
                'RESOLVED'
            )
        ),

    CONSTRAINT chk_alert_source
        CHECK (
            source = 'open_meteo'
        )
);


CREATE TABLE IF NOT EXISTS pipeline_run_logs (
    run_id VARCHAR(100) PRIMARY KEY,

    pipeline_name VARCHAR(150) NOT NULL,
    source VARCHAR(50) NOT NULL,

    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,

    status VARCHAR(30) NOT NULL,

    records_extracted INTEGER
        NOT NULL DEFAULT 0,

    records_loaded INTEGER
        NOT NULL DEFAULT 0,

    error_message TEXT,
    duration_seconds DOUBLE PRECISION,

    created_at TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_pipeline_status
        CHECK (
            status IN (
                'RUNNING',
                'SUCCESS',
                'PARTIAL_SUCCESS',
                'FAILED'
            )
        ),

    CONSTRAINT chk_pipeline_records_extracted
        CHECK (
            records_extracted >= 0
        ),

    CONSTRAINT chk_pipeline_records_loaded
        CHECK (
            records_loaded >= 0
        ),

    CONSTRAINT chk_pipeline_duration
        CHECK (
            duration_seconds IS NULL
            OR duration_seconds >= 0
        )
);


CREATE TABLE IF NOT EXISTS data_quality_logs (
    check_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    run_id VARCHAR(100) NOT NULL,
    check_name VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL,

    bad_records_count INTEGER
        NOT NULL DEFAULT 0,

    message TEXT,

    created_at TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_data_quality_pipeline_run
        FOREIGN KEY (run_id)
        REFERENCES pipeline_run_logs (run_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_data_quality_status
        CHECK (
            status IN (
                'PASSED',
                'FAILED',
                'WARNING'
            )
        ),

    CONSTRAINT chk_data_quality_bad_count
        CHECK (
            bad_records_count >= 0
        ),

    CONSTRAINT uq_data_quality_run_check
        UNIQUE (
            run_id,
            check_name
        )
);


DROP TRIGGER IF EXISTS
    trg_dim_location_updated_at
ON dim_location;


CREATE TRIGGER trg_dim_location_updated_at
BEFORE UPDATE ON dim_location
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


DROP TRIGGER IF EXISTS
    trg_dim_monitoring_point_updated_at
ON dim_monitoring_point;


CREATE TRIGGER trg_dim_monitoring_point_updated_at
BEFORE UPDATE ON dim_monitoring_point
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();